image: atlassian/default-image:2

pipelines:
  branches:
    faisal:
      - step:
          name: "Build and test"
          script:
            - zip -r app.zip .
          artifacts: 
            - app.zip
      - step:
          name: "Deploy to Production"
          deployment: production
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.0
              variables:
                AZURE_APP_ID: "4de84853-ed00-4a97-8cde-6ceb50f0aa45"
                AZURE_PASSWORD: "CNKBu9vYHfLO5G8p8TK/Y3C/M9gHqmdbXJlE9yrKbjw="
                AZURE_TENANT_ID: "79f98730-bd58-4467-b7cc-d19433d3d1ec"
                AZURE_RESOURCE_GROUP: 'digital-attendance'
                AZURE_APP_NAME: 'digital-attendance'
                ZIP_FILE: 'app.zip'

